name: geosci-labs-dev

channels:
  - conda-forge
dependencies:
  - cvxopt
  - deepdish
  - discretize
  - empymod
  - ipywidgets>=0.6.0
  - jupyter
  - matplotlib<3.5
  - Pillow
  - pip
  - pymatsolver
  - requests
  - simpeg
  - pytest
  - flake8
  - black
  - pip:
    - testipynb

